r = read.table("comparison_contents.txt")
jpeg("comparison_contents.jpg")
boxplot(r$V1,r$V2,r$V3,r$V4,names=c("Extant", "True_trees", "IQ_trees", "Treerecs"), border=c("black", "green", "red","blue"), notch=TRUE,title="Gene content")
dev.off()
r = read.table("comparison_degrees.txt")
jpeg("comparison_degrees.jpg")
plot(r$V1,r$V5,type="l",col="black",lwd=2,xlim=c(0,7),xlab="number of neighbors",ylab="frequency")
points(r$V1,r$V3,type="l",col="red",lwd=2)
points(r$V1,r$V2,type="l",col="green",lwd=2)
points(r$V1,r$V4,type="l",col="blue",lwd=2)
